---
title: "Removing aqutic plants from IUCN species list"
output:
  html_document:
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  word_document:
    toc: yes
date: "2024-08-21"
---

## Libraries required

```{r, message = F}
library(tidyverse)
library(data.table)
```

## Read in Data
```{r}
plantsonIUCN <- read.csv("Data/Raw Data/assessments.csv") %>%
  select(-language, -rationale, -threats, -population, -populationTrend, -range, -useTrade, -conservationActions, -yearLastSeen, -scopes)

growthform <- fread("Data/32845.txt", fill = TRUE)

#this is a huge dataset with lots of values and is just generally extremely messy - first discovered that the value with most information is the "growth form complete" value

growthformcomplete <- growthform %>%
  filter(OriglName == "growth form complete") %>%
  dplyr::rename(scientificName = SpeciesName) 

IUCNdatawithgrowthform1 <- left_join(plantsonIUCN, growthformcomplete, by = "scientificName") %>%
  select(scientificName, redlistCategory, systems, OrigValueStr, Reference) %>%
  dplyr::rename(GrowthForm = OrigValueStr) %>%
  dplyr::rename(ReferenceforGrowthForm = Reference) %>%
  distinct(scientificName, .keep_all = TRUE)

#this data gives us around 50% of all species growth forms in our drought dataset

#now to try and fill in the gaps here - run the same thing with other growth-form metrics

#take just the species that haven't been covered by that dataset

IUCNgrowthformnotcovered1 <- IUCNdatawithgrowthform1 %>%
  filter(is.na(GrowthForm))

#left_join this with some growth form data

#first pull anything called growth form from TRY

growthformany <- growthform %>%
  dplyr::rename(scientificName = SpeciesName) %>%
  filter(str_detect(OriglName, "(?i)growth form|(?i)growthform|(?i)growth_form")) %>%
  filter(OriglName != "growth form complete") #remove growth forms that are already accounted for

#join this back with previous data to just have info for our speceies

IUCNdatawithgrowthform2 <- left_join(IUCNgrowthformnotcovered1, growthformany, by = "scientificName") %>%
  select(scientificName, redlistCategory, systems, OrigValueStr, Reference) %>%
  dplyr::rename(GrowthForm = OrigValueStr) %>%
  dplyr::rename(ReferenceforGrowthForm = Reference) %>%
  distinct(scientificName, .keep_all = TRUE)

IUCNgrowthformnotcovered2 <- IUCNdatawithgrowthform2 %>%
  filter(is.na(GrowthForm))  

## covered around 2000 more species but we still have 2000 with missing data

#try other data types e.g. "habit"

habit <- growthform %>%
  dplyr::rename(scientificName = SpeciesName) %>%
  filter(str_detect(OriglName, "(?i)habit")) %>%
  filter(!str_detect(OriglName, "(?i)habitat|(?i)microhabit")) #trying species habit but not habitat or microhabitat

IUCNdatawithgrowthform3 <- left_join(IUCNgrowthformnotcovered2, habit, by = "scientificName") %>%
  select(scientificName, redlistCategory, systems, OrigValueStr, Reference) %>%
  dplyr::rename(GrowthForm = OrigValueStr) %>%
  dplyr::rename(ReferenceforGrowthForm = Reference) %>%
  distinct(scientificName, .keep_all = TRUE)

IUCNgrowthformnotcovered3 <- IUCNdatawithgrowthform3 %>%
  filter(is.na(GrowthForm))  

#plant habit covered literally one single species in our list - still a lot to go

# try "life form" or "plant form" or 

formvague <- growthform %>%
  dplyr::rename(scientificName = SpeciesName) %>%
  filter(str_detect(OriglName, "(?i)L-form|(?i)life form|(?i)life_form|(?i)life stage|(?i)main_growth_form|(?i)plant form|(?i)SpeciesLifeForm"))

IUCNdatawithgrowthform4 <- left_join(IUCNgrowthformnotcovered3, formvague, by = "scientificName") %>%
  select(scientificName, redlistCategory, systems, OrigValueStr, Reference) %>%
  dplyr::rename(GrowthForm = OrigValueStr) %>%
  dplyr::rename(ReferenceforGrowthForm = Reference) %>%
  distinct(scientificName, .keep_all = TRUE)

IUCNgrowthformnotcovered4 <- IUCNdatawithgrowthform4 %>%
  filter(is.na(GrowthForm))  

##and life form gave us four more species... still going...

#tried a whole bunch of others but clear that out species aren't necessarily covered for their growth form in this TRY data

# so now just checking what realms these remaining species that we don't know the growth form of are

# merge all that info back together


df_list <- list(filter(IUCNdatawithgrowthform1, !is.na(GrowthForm)),
                filter(IUCNdatawithgrowthform2, !is.na(GrowthForm)), 
                filter(IUCNdatawithgrowthform3, !is.na(GrowthForm)),
                filter(IUCNdatawithgrowthform4, !is.na(GrowthForm)),
                IUCNgrowthformnotcovered4)

# now put all this data back together and see the spread of species left that don't have growth form data on TRY

fullIUCNandgrowthform <- df_list %>%
  reduce(full_join, by=c('scientificName', 'redlistCategory', 'systems', 'GrowthForm', 'ReferenceforGrowthForm')) %>%
  mutate(Aquatic = ifelse(grepl("aqua|float", GrowthForm, ignore.case = TRUE),'yes',
                          ifelse(systems == "Freshwater (=Inland waters)" & is.na(GrowthForm) | systems == "Marine" & is.na(GrowthForm) | systems == "Freshwater (=Inland waters)|Marine"  & is.na(GrowthForm), 'yes', 'no'))) %>% #make a column for if the species is aquatic or not
  mutate(Aquatic = ifelse(is.na(Aquatic), 'yes', Aquatic))



#great now we can use this as the official list of species to remove aquatic species in further analyses
```

<br>

Quick plot for aquatic plants specifically

```{r}
aquaticnessplot <- ggplot(data = fullIUCNandgrowthform, aes(Aquatic, fill = Aquatic)) +
  geom_bar(position= "dodge") +
  scale_fill_manual(name = "Aquatic", values = c("#7D5D3A", "#53619E")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(y = "Species Count (log10 transformed)", x = "") +
  guides(fill="none")
plot(aquaticnessplot)
```

<br> 
Saving the relevant data for later!

```{r}
write.csv(fullIUCNandgrowthform, "Data/Data Used in Analyses/fullIUCNandgrowthform.csv")
```

